vr-prt/airb_in_game

Gemfile
Gemfile.lock
app/models/user.rb
app/views/devise/confirmations/new.html.erb
app/views/devise/mailer/confirmation_instructions.html.erb
app/views/devise/mailer/email_changed.html.erb
app/views/devise/mailer/password_change.html.erb
app/views/devise/mailer/reset_password_instructions.html.erb
app/views/devise/mailer/unlock_instructions.html.erb
app/views/devise/passwords/edit.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_error_messages.html.erb
app/views/devise/shared/_links.html.erb
app/views/devise/unlocks/new.html.erb
app/views/layouts/application.html.erb
config/environments/development.rb
config/initializers/devise.rb
config/locales/devise.en.yml
config/routes.rb
db/migrate/20220815194634_devise_create_users.rb
db/schema.rb
test/models/user_test.rb

- Added devise gem
- Added config to devise
- Generated the User model
- Tested user sign in
Where to test:
GOTO : "/users/sign_up"
Screenshot of sign up page:
Please review @jchau905 @julienLeMee

Create user model

---

app/assets/stylesheets/components/_footer.scss
app/views/layouts/application.html.erb
app/views/pages/_footer.html.erb
app/views/pages/_navbar.html.erb
app/views/pages/home.html.erb

@vr-prt @MikaelJG 
Added:
Navbar,
Footer,
Logo

Added Nav-Bar & Footer Along with Logo

---

app/controllers/game_worlds_controller.rb
app/models/game_world.rb
app/models/user.rb
app/views/game_worlds/index.html.erb
app/views/game_worlds/new.html.erb
app/views/game_worlds/show.html.erb
config/routes.rb
db/migrate/20220815204105_create_game_worlds.rb
db/schema.rb
test/controllers/game_worlds_controller_test.rb
test/models/game_world_test.rb

**What has changed**:
- Generated a game world model
- Generated a game worlds controller
- Added index, new, create, show and game world params methods
- Added index, new and show views
- Tested creation of a new game world
**Where to test**:
- Log-in at '/users/sign_in'
- GOTO '/game_worlds/new' and create a new game
- GOTO '/game_worlds/' and '/game_worlds/:game_world_id' to view index and show page
**Screenshots**:
Please review @jchau905 @julienLeMee

Add game world model

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/components/_search_bar.scss
app/views/layouts/application.html.erb
app/views/pages/_navbar.html.erb
app/views/pages/home.html.erb

Added:
Search bar to Nav Bar
Added imports scss to index.scss
Changed:
Logo
Removed:
Unrelated Content on Home-Page

Added SearchBar in Navbar + Changed the Logo

---

Gemfile.lock
app/assets/stylesheets/components/_game_worlds_cards.scss
app/assets/stylesheets/components/_index.scss
app/views/pages/_game_worlds_cards.html.erb
app/views/pages/home.html.erb

Add a prototype for a game worlds cards
> cards with background image and title
wait for your return @vr-prt @ MikaelJG

Game worlds cards

---

app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/components/_search_bar.scss
app/assets/stylesheets/pages/_home.scss
app/views/layouts/application.html.erb
app/views/shared/_footer.html.erb
app/views/shared/_navbar.html.erb

@MikaelJG @vr-prt 
Fixed Navbar/ Searchbar/ Rendering/ Background Color

Fixed the Searchbar/Rendering/Background

---

app/controllers/application_controller.rb
app/controllers/game_worlds_controller.rb
app/controllers/pages_controller.rb

- Requested an authentification for all the pages except homepage, the index and the showpages of game worlds.
How to test:
GOTO '/game_worlds/new' without being logged-in for instance.

Add authentification to app

---

Gemfile
Gemfile.lock
db/seeds.rb

What was added: 
-in db/seed.rb, the creation of both users and game worlds. 
-in gemfile, the gem "faker" requirement. 
TODO: 
-TEST, After pull origin master, and bundle install, rails db:seed
please review @vr-prt

seed user gameworld creation

---

db/seeds.rb

Minor adjustement of former merged branch
deleted notes in seeds.rb
@vr-prt

deleted comments

---

db/seeds.rb

- Filled the seed with users and game worlds
How to test:
- Bundle install
- Run rails db:seed to create 20 users and game worlds associated with a user

Worked on seed with users and game worlds

---

app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/pages/_home.scss
app/views/pages/home.html.erb
app/views/shared/_navbar.html.erb

@MikaelJG @vr-prt @julienLeMee 
Added:
Banner /w Clickable link to Game Worlds
Login Feature redirects
Log Out Feature redirects
Logo Color

Landing page banner

---

app/assets/stylesheets/components/_cards.scss
app/assets/stylesheets/components/_index.scss
app/views/game_worlds/index.html.erb
app/views/game_worlds/show.html.erb
app/views/shared/_game_worlds_cards.html.erb

just starting to game_worlds_cards, it's not finish, I'm waiting for the seed
@MikaelJG @vr-prt

starting the game worlds cards for the homepage

---

app/views/game_worlds/index.html.erb

changing one star rating
@MikaelJG

change rating stars

---

app/controllers/application_controller.rb
app/models/user.rb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb

- Added a username on sign up and sign in
- Removed user validations which were overriting devise one's
How to test:
GOTO '/users/sign_up' and try signing up

Added username on sign up

---

app/controllers/reservations_controller.rb
app/models/game_world.rb
app/models/reservation.rb
app/models/user.rb
db/migrate/20220816184252_create_reservations.rb
db/schema.rb
test/controllers/reservations_controller_test.rb
test/models/reservation_test.rb

Added: 
- generated reservations table with association on user and game world models
- generated reservation controller
please review @vr-prt

Reservation table to database

---

app/controllers/game_worlds_controller.rb
app/views/shared/_navbar.html.erb

- Connected the navbar form the the game worlds controller.
- Added a search for a game world feature in the game worlds index method.
How to test:
GOTO: Anywhere in the website and search for a game world.
Or GOTO '/game-worlds' to see all the game worlds.
Screen:

Add search game worlds

---

db/seeds.rb

Added
-reservation create in the seed with appropriate association
-message of creation to user in console
-delete_all for reservation
To test:
-rails db:seed
snapshot
review @vr-prt @julienLeMee

updated date values, descriptive message and reservation deletion

---

app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/components/_cards.scss
app/views/game_worlds/index.html.erb
app/views/pages/home.html.erb
app/views/shared/_game_worlds_cards.html.erb

I update the display of all game worlds
- put a banner but I think we can change it for another one
- cards for each world, and when you click on a name of the world, wo go to the page of the world
- add a button for a "reservation"
@MikaelJG @vr-prt

Game cards index page

---

app/controllers/reservations_controller.rb
app/models/reservation.rb
app/views/reservations/index.html.erb
app/views/reservations/new.html.erb
app/views/reservations/show.html.erb
config/routes.rb

- Added all the 7 reservations routes
- Added index, show, new and create methods to reservations controller
- Added index and show views*
How to test:
GOTO: '/reservations' to see all the reservations or '/reservations/1' to see a reservation example
GOTO: '/game_worlds/:game_world_id/reservations/new' to create a reservation (make sure to be logged-in)
Screens:

Add reservations routes, actions and views

---

app/assets/stylesheets/components/_cards.scss
app/views/game_worlds/index.html.erb

change background banner, add a buton for filter on index page
- add a button
- custom the reservation button
- change banner background
- 

change background banner, add a buton for filter on index page

---

app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_show_game_worlds.scss
app/assets/stylesheets/pages/_home.scss
app/views/game_worlds/show.html.erb
app/views/layouts/application.html.erb
app/views/shared/_navbar.html.erb

@MikaelJG @vr-prt @julienLeMee 
Added:
Routing to Reserve Now on Game_worlds Show Page

Finished Routing Reserve Now on Game_Worlds Show Page

---

app/views/reservations/show.html.erb

- Added reservations infos to a reservation showpage
- Reservation status == 0 : Pending
- Reservation status == 1 : Confirmed
- Reservation status == 2 : Done
Where to test:
GOTO '/reservations/4' for instance to see a confirmed reservation
Screen:

Added infos to reservation show

---

app/assets/stylesheets/components/_button.scss
app/views/reservations/new.html.erb

Added a Go Back Button on Reservation/New page

---

app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_cards.scss
app/views/game_worlds/index.html.erb
app/views/game_worlds/new.html.erb

I change the filter button to an added, I update his position and I custom it
@MikaelJG  @vr-prt

change the filter button to an added button

---

app/controllers/reservations_controller.rb
app/views/reservations/edit.html.erb
app/views/reservations/index.html.erb
app/views/reservations/new.html.erb
app/views/reservations/show.html.erb

- Added edit, update, and destroy methods to reservations controller
- Added edit view with edit form
- Added infos to the reservations index
How to test:
GOTO '/reservations/3' for instance and try to edit a reservation or to delete one.
Screen:

Add edit and destroy to reservations

---

app/assets/stylesheets/components/_navbar.scss
app/views/layouts/application.html.erb
app/views/shared/_navbar.html.erb

Nav Bar Fixed to Top

---

app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_icons_homepage.scss
app/assets/stylesheets/components/_index.scss
app/views/pages/home.html.erb
app/views/shared/_footer.html.erb

added a three icons on the bottom of homepage 
do you want a border around icons ?

added icons on homepage

---

app/assets/stylesheets/components/_button.scss
app/views/reservations/show.html.erb

added a go back button on a reservation page after a booking by user

added a go back button on reservation page

---

app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/components/_cards.scss
app/assets/stylesheets/pages/_home.scss
app/views/reservations/index.html.erb
app/views/shared/_navbar.html.erb

Added:
Image to /reservations
Cards to /reservations
margin top to body

Added images/cards to the /reservations page, added a top margin to body

---

app/models/reservation.rb
db/seeds.rb

- Adding a main user with 3 main game worlds and 3 main reservations
How to test:
RUN 'rails db:seed'

Upgraded seed by adding main user, main games and main reservations

---

app/views/shared/_navbar.html.erb

just redirected links in navbar

fixed link in navbar

---

app/views/game_worlds/new.html.erb
app/views/reservations/edit.html.erb
app/views/shared/_navbar.html.erb

@MikaelJG 
Added go back buttons on all forms

Go back buttons

---

app/views/shared/_navbar.html.erb

fixed my bookings path

---

app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_cards.scss
app/assets/stylesheets/pages/_home.scss
app/views/devise/sessions/new.html.erb
app/views/game_worlds/index.html.erb
app/views/reservations/index.html.erb
app/views/shared/_game_worlds_cards.html.erb

- added gradient for game worlds index page
- put a log-in form in a container
- added a tag/icon for the status reservation
- added dates on reservations cards

Added tag and dates on reservations cards

---

app/assets/stylesheets/components/_avatar.scss
app/views/shared/_navbar.html.erb

- added a profil photo for a user
- add-world-link in a navbar menu
- 
@MikaelJG

added a profil photo for a user and a add-world-link in a navbar menu

---

app/controllers/game_worlds_controller.rb
app/models/game_world.rb
app/views/game_worlds/edit.html.erb
app/views/game_worlds/my_game_worlds.html.erb
app/views/game_worlds/show.html.erb
config/routes.rb

- Added a my game worlds path
- Added edit update and destroy methods to game worlds controller
- Refactored search, now possible to search by description of game worlds
How to test:
- GOTO '/my_game_worlds' to see only the game worlds you've created
- GOTO one of your game world and try to delete one
Screens:

Add owner "my game worlds" and refactored search

---

.gitignore
Gemfile
Gemfile.lock
app/controllers/game_worlds_controller.rb
app/models/game_world.rb
app/views/game_worlds/new.html.erb
app/views/shared/_game_worlds_cards.html.erb
config/environments/development.rb
config/storage.yml
db/migrate/20220818150012_create_active_storage_tables.active_storage.rb
db/schema.rb

@MikaelJG 
Cloudinary Configured

Cloudinary to create world

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_form.scss
app/assets/stylesheets/components/_index.scss
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_links.html.erb
app/views/game_worlds/new.html.erb

I custom a forms for log-in and for added a game

custom a form for log-in and for add a game

---

.gitignore
app/views/game_worlds/new.html.erb

fix new game wolrd form

---

app/models/reservation.rb
app/views/reservations/index.html.erb
db/seeds.rb

Changes:
- Changed the reservations status which now uses enums
- From now use Reservation.status == "pending", "confirmed", or "done" to check status of reservation
Screen:

Updated reservations by adding enums to status

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_footer.scss
app/views/game_worlds/show.html.erb
app/views/layouts/application.html.erb
app/views/shared/_footer.html.erb
db/schema.rb

@MikaelJG 
Added:
Footer fixed to bottom of page
Changed Home page Button from blue to orange
Changed the delete world button color to red on show page

Footer to end

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_show_game_worlds.scss
app/views/game_worlds/index.html.erb
app/views/game_worlds/show.html.erb
app/views/layouts/application.html.erb
app/views/shared/_footer.html.erb
db/schema.rb

Changed font and added Edit button on Show Page

Buttons font edit

---

app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/components/_icons_homepage.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/pages/_home.scss
app/views/pages/home.html.erb

change a homepage background and position title and a button
@MikaelJG

change background home page

---

app/views/game_worlds/edit.html.erb
app/views/reservations/edit.html.erb
app/views/reservations/new.html.erb
app/views/reservations/show.html.erb
app/views/shared/_navbar.html.erb

Logo is fixed

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_map.scss
app/controllers/game_worlds_controller.rb
app/javascript/controllers/index.js
app/javascript/controllers/map_controller.js
app/views/game_worlds/_info_window.html.erb
app/views/game_worlds/index.html.erb
app/views/layouts/application.html.erb
db/seeds.rb

added:
-mapbox config and path to /gameworld_path. 
Snapshot: 
please review @julienLeMee

Mapbox config

---

app/views/game_worlds/index.html.erb
app/views/layouts/application.html.erb

-fixed map default layout on all pages. 
please review @julienLeMee

cleaned map display

---

app/views/game_worlds/index.html.erb

Added:
-Resetted api key
please review @julienLeMee ! :)

map API key fix

---

app/controllers/reservations_controller.rb
app/models/game_world.rb
app/models/reservation.rb
app/models/user.rb
app/views/reservations/owner_reservation.html.erb
app/views/reservations/owner_reservations.html.erb
config/routes.rb

- Added confirm or decline reservation for the owner
- Added owner reservations routes
- Added owner reservations methods on reservations controller
- Added owner reservations and owner reservation views
How to test:
GOTO : '/owner_reservations' and '/owner_reservation/:id' to see all the booking requests of other users to your game worlds
Screens:

Add owner reservations

---

app/controllers/game_worlds_controller.rb
db/seeds.rb

Added:
-working markers on game_worlds page
-better seed address. 
Please review @vr-prt

geocoder understands seed addresses

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_cards.scss
app/assets/stylesheets/pages/_home.scss
app/views/reservations/show.html.erb

> custom cards for reservations

custom cards for reservations

---

app/assets/stylesheets/components/_show_game_worlds.scss
app/controllers/game_worlds_controller.rb
app/models/game_world.rb
app/views/game_worlds/new.html.erb
app/views/game_worlds/show.html.erb
app/views/shared/_game_worlds_cards.html.erb

@MikaelJG 
Cloudinary Photo Upload

Cloudinary images

---

app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/components/_cards.scss
app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/components/_show_game_worlds.scss
app/assets/stylesheets/pages/_home.scss
app/views/devise/registrations/edit.html.erb
app/views/game_worlds/show.html.erb
app/views/reservations/edit.html.erb
app/views/reservations/index.html.erb
app/views/reservations/owner_reservation.html.erb
app/views/reservations/owner_reservations.html.erb
app/views/shared/_footer.html.erb
app/views/shared/_navbar.html.erb
f

Cleaned up a lot of useless CSS code and fixed the footer and some background colors

Fixed the Footer, Resized the show image, Cleaned up Useless CSS code

---

app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_icons_homepage.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/pages/_home.scss
app/javascript/controllers/typed_js_controller.js

Fixed landing page colors

---

app/assets/stylesheets/components/_cards.scss
app/views/reservations/owner_reservations.html.erb

styling cards for owner reservations

cards for owner reservation

---

config/environments/production.rb

Changed:
Fixed cloudinary config on production

Fixed cloudinary config on production

---

app/assets/stylesheets/components/_map.scss
app/views/game_worlds/show.html.erb

Added:
-map on game world page
snapshot:
please review @julienLeMee

Display map in show

---

app/assets/stylesheets/components/_icons_homepage.scss
app/views/reservations/index.html.erb
app/views/reservations/owner_reservations.html.erb
app/views/reservations/show.html.erb
app/views/shared/_navbar.html.erb

custom cards booking request for all reservations and owner_reservations
@MikaelJG

custom cards booking request

---

app/views/reservations/index.html.erb

@julienLeMee Fixed image on my bookings

Fixed Cloudinary image on My Bookings

---

app/views/game_worlds/my_game_worlds.html.erb

juste fix one button style color
@MikaelJG

Button custom

---

app/assets/stylesheets/components/_map.scss
app/controllers/game_worlds_controller.rb
app/views/game_worlds/index.html.erb
app/views/game_worlds/show.html.erb

- Added map to each game world with one marker
- Restyled style of the map on the index and on the show
Screens:

Added map to game world and added style

---

app/models/game_world.rb
app/views/game_worlds/new.html.erb

limit to 3 photos uploading when creating game-world

Limit Cloudinary Upload Image

---

app/views/reservations/index.html.erb
app/views/reservations/owner_reservations.html.erb

Fixed the order of reservations and owner reservations
Screens:

Fixed order of reservation statuses

---

app/assets/stylesheets/components/_form.scss
app/views/reservations/owner_reservation.html.erb

fixed style booking confirmation
@vr-prt

status_booking fixed style
